//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpAddress { get; set; }
        public Nullable<decimal> EmpSalary { get; set; }
        public string Job { get; set; }
    }
}
