//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblservice
    {
        public int Id { get; set; }
        public string ServiceName { get; set; }
        public string Details { get; set; }
        public string Img1 { get; set; }
        public string Img2 { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
