//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DummyMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstudent
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public string StudentAddress { get; set; }
        public string City { get; set; }
        public Nullable<int> EmpId { get; set; }
    }
}
